/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is auto-generated by `next dev`/`next build` normally.
// Committed here only so the scaffold type-checks before your first run.
