-- Seeds role_permissions from the same source-of-truth matrix as
-- lib/roleSeedData.ts (see gen_permissions.py). Regenerate together —
-- do not hand-edit one without the other.

with perms(role_name, module, can_view, can_add, can_edit, can_delete, can_approve) as (
  values
    ('System Administrator', 'system_config', true, true, true, true, false),
    ('System Administrator', 'audit_log', true, false, false, false, false),
    ('System Administrator', 'employees', true, true, true, true, false),
    ('System Administrator', 'organization', true, true, true, true, false),
    ('System Administrator', 'leave', true, true, true, true, false),
    ('System Administrator', 'documents', true, true, true, true, false),
    ('System Administrator', 'requests', true, true, true, true, false),
    ('System Administrator', 'procurement', true, true, true, true, false),
    ('System Administrator', 'it_support', true, true, true, true, false),
    ('System Administrator', 'assets', true, true, true, true, false),
    ('System Administrator', 'inventory', true, true, true, true, false),
    ('System Administrator', 'expenses', true, true, true, true, false),
    ('System Administrator', 'budgets', true, true, true, true, false),
    ('System Administrator', 'calendar', true, true, true, true, false),
    ('System Administrator', 'communication', true, true, true, true, false),
    ('System Administrator', 'reports', true, true, true, true, false),
    ('HR Manager', 'system_config', false, false, false, false, false),
    ('HR Manager', 'audit_log', true, false, false, false, false),
    ('HR Manager', 'employees', true, true, true, true, false),
    ('HR Manager', 'organization', true, true, true, false, false),
    ('HR Manager', 'leave', true, true, true, true, false),
    ('HR Manager', 'documents', true, true, true, false, false),
    ('HR Manager', 'requests', true, false, false, false, false),
    ('HR Manager', 'procurement', false, false, false, false, false),
    ('HR Manager', 'it_support', false, false, false, false, false),
    ('HR Manager', 'assets', false, false, false, false, false),
    ('HR Manager', 'inventory', false, false, false, false, false),
    ('HR Manager', 'expenses', true, false, false, false, false),
    ('HR Manager', 'budgets', true, false, false, false, false),
    ('HR Manager', 'calendar', true, true, true, false, false),
    ('HR Manager', 'communication', true, true, true, false, false),
    ('HR Manager', 'reports', true, true, true, true, false),
    ('HR Officer', 'system_config', false, false, false, false, false),
    ('HR Officer', 'audit_log', false, false, false, false, false),
    ('HR Officer', 'employees', true, true, true, false, false),
    ('HR Officer', 'organization', true, false, false, false, false),
    ('HR Officer', 'leave', true, true, true, false, false),
    ('HR Officer', 'documents', true, true, true, false, false),
    ('HR Officer', 'requests', true, false, false, false, false),
    ('HR Officer', 'procurement', false, false, false, false, false),
    ('HR Officer', 'it_support', false, false, false, false, false),
    ('HR Officer', 'assets', false, false, false, false, false),
    ('HR Officer', 'inventory', false, false, false, false, false),
    ('HR Officer', 'expenses', false, false, false, false, false),
    ('HR Officer', 'budgets', false, false, false, false, false),
    ('HR Officer', 'calendar', true, true, true, false, false),
    ('HR Officer', 'communication', true, false, false, false, false),
    ('HR Officer', 'reports', true, false, false, false, false),
    ('Department Manager', 'system_config', false, false, false, false, false),
    ('Department Manager', 'audit_log', false, false, false, false, false),
    ('Department Manager', 'employees', true, false, false, false, false),
    ('Department Manager', 'organization', false, false, false, false, false),
    ('Department Manager', 'leave', true, false, false, false, true),
    ('Department Manager', 'documents', true, true, true, false, false),
    ('Department Manager', 'requests', true, false, false, false, true),
    ('Department Manager', 'procurement', true, false, false, false, true),
    ('Department Manager', 'it_support', true, false, false, false, false),
    ('Department Manager', 'assets', true, false, false, false, false),
    ('Department Manager', 'inventory', false, false, false, false, false),
    ('Department Manager', 'expenses', true, false, false, false, true),
    ('Department Manager', 'budgets', true, false, false, false, false),
    ('Department Manager', 'calendar', true, true, true, false, false),
    ('Department Manager', 'communication', true, false, false, false, false),
    ('Department Manager', 'reports', true, false, false, false, false),
    ('Supervisor', 'system_config', false, false, false, false, false),
    ('Supervisor', 'audit_log', false, false, false, false, false),
    ('Supervisor', 'employees', true, false, false, false, false),
    ('Supervisor', 'organization', false, false, false, false, false),
    ('Supervisor', 'leave', true, false, false, false, true),
    ('Supervisor', 'documents', true, false, false, false, false),
    ('Supervisor', 'requests', true, false, false, false, true),
    ('Supervisor', 'procurement', true, false, false, false, true),
    ('Supervisor', 'it_support', false, false, false, false, false),
    ('Supervisor', 'assets', false, false, false, false, false),
    ('Supervisor', 'inventory', false, false, false, false, false),
    ('Supervisor', 'expenses', true, false, false, false, true),
    ('Supervisor', 'budgets', false, false, false, false, false),
    ('Supervisor', 'calendar', true, true, true, false, false),
    ('Supervisor', 'communication', true, false, false, false, false),
    ('Supervisor', 'reports', true, false, false, false, false),
    ('IT Officer', 'system_config', false, false, false, false, false),
    ('IT Officer', 'audit_log', false, false, false, false, false),
    ('IT Officer', 'employees', true, false, false, false, false),
    ('IT Officer', 'organization', false, false, false, false, false),
    ('IT Officer', 'leave', false, false, false, false, false),
    ('IT Officer', 'documents', true, false, false, false, false),
    ('IT Officer', 'requests', false, false, false, false, false),
    ('IT Officer', 'procurement', false, false, false, false, false),
    ('IT Officer', 'it_support', true, true, true, true, false),
    ('IT Officer', 'assets', true, true, true, true, false),
    ('IT Officer', 'inventory', false, false, false, false, false),
    ('IT Officer', 'expenses', false, false, false, false, false),
    ('IT Officer', 'budgets', false, false, false, false, false),
    ('IT Officer', 'calendar', true, true, true, false, false),
    ('IT Officer', 'communication', true, false, false, false, false),
    ('IT Officer', 'reports', true, false, false, false, false),
    ('Procurement Officer', 'system_config', false, false, false, false, false),
    ('Procurement Officer', 'audit_log', false, false, false, false, false),
    ('Procurement Officer', 'employees', false, false, false, false, false),
    ('Procurement Officer', 'organization', false, false, false, false, false),
    ('Procurement Officer', 'leave', false, false, false, false, false),
    ('Procurement Officer', 'documents', true, false, false, false, false),
    ('Procurement Officer', 'requests', false, false, false, false, false),
    ('Procurement Officer', 'procurement', true, true, true, true, false),
    ('Procurement Officer', 'it_support', false, false, false, false, false),
    ('Procurement Officer', 'assets', false, false, false, false, false),
    ('Procurement Officer', 'inventory', true, true, true, true, false),
    ('Procurement Officer', 'expenses', true, false, false, false, false),
    ('Procurement Officer', 'budgets', true, false, false, false, false),
    ('Procurement Officer', 'calendar', true, true, true, false, false),
    ('Procurement Officer', 'communication', true, false, false, false, false),
    ('Procurement Officer', 'reports', true, false, false, false, false),
    ('Finance Officer', 'system_config', false, false, false, false, false),
    ('Finance Officer', 'audit_log', false, false, false, false, false),
    ('Finance Officer', 'employees', false, false, false, false, false),
    ('Finance Officer', 'organization', false, false, false, false, false),
    ('Finance Officer', 'leave', false, false, false, false, false),
    ('Finance Officer', 'documents', true, false, false, false, false),
    ('Finance Officer', 'requests', false, false, false, false, false),
    ('Finance Officer', 'procurement', true, false, false, false, false),
    ('Finance Officer', 'it_support', false, false, false, false, false),
    ('Finance Officer', 'assets', false, false, false, false, false),
    ('Finance Officer', 'inventory', false, false, false, false, false),
    ('Finance Officer', 'expenses', true, true, true, true, false),
    ('Finance Officer', 'budgets', true, true, true, true, false),
    ('Finance Officer', 'calendar', true, true, true, false, false),
    ('Finance Officer', 'communication', true, false, false, false, false),
    ('Finance Officer', 'reports', true, true, true, true, false),
    ('Office Administrator', 'system_config', false, false, false, false, false),
    ('Office Administrator', 'audit_log', false, false, false, false, false),
    ('Office Administrator', 'employees', true, false, false, false, false),
    ('Office Administrator', 'organization', false, false, false, false, false),
    ('Office Administrator', 'leave', false, false, false, false, false),
    ('Office Administrator', 'documents', true, true, true, true, false),
    ('Office Administrator', 'requests', true, true, true, false, false),
    ('Office Administrator', 'procurement', false, false, false, false, false),
    ('Office Administrator', 'it_support', false, false, false, false, false),
    ('Office Administrator', 'assets', false, false, false, false, false),
    ('Office Administrator', 'inventory', false, false, false, false, false),
    ('Office Administrator', 'expenses', false, false, false, false, false),
    ('Office Administrator', 'budgets', false, false, false, false, false),
    ('Office Administrator', 'calendar', true, true, true, true, false),
    ('Office Administrator', 'communication', true, true, true, true, false),
    ('Office Administrator', 'reports', true, false, false, false, false),
    ('Employee', 'system_config', false, false, false, false, false),
    ('Employee', 'audit_log', false, false, false, false, false),
    ('Employee', 'employees', false, false, false, false, false),
    ('Employee', 'organization', false, false, false, false, false),
    ('Employee', 'leave', true, false, false, false, false),
    ('Employee', 'documents', true, false, false, false, false),
    ('Employee', 'requests', true, false, false, false, false),
    ('Employee', 'procurement', false, false, false, false, false),
    ('Employee', 'it_support', true, false, false, false, false),
    ('Employee', 'assets', false, false, false, false, false),
    ('Employee', 'inventory', false, false, false, false, false),
    ('Employee', 'expenses', true, false, false, false, false),
    ('Employee', 'budgets', false, false, false, false, false),
    ('Employee', 'calendar', true, false, false, false, false),
    ('Employee', 'communication', true, false, false, false, false),
    ('Employee', 'reports', false, false, false, false, false),
    ('Auditor', 'system_config', false, false, false, false, false),
    ('Auditor', 'audit_log', true, false, false, false, false),
    ('Auditor', 'employees', true, false, false, false, false),
    ('Auditor', 'organization', false, false, false, false, false),
    ('Auditor', 'leave', true, false, false, false, false),
    ('Auditor', 'documents', true, false, false, false, false),
    ('Auditor', 'requests', true, false, false, false, false),
    ('Auditor', 'procurement', true, false, false, false, false),
    ('Auditor', 'it_support', true, false, false, false, false),
    ('Auditor', 'assets', true, false, false, false, false),
    ('Auditor', 'inventory', true, false, false, false, false),
    ('Auditor', 'expenses', true, false, false, false, false),
    ('Auditor', 'budgets', true, false, false, false, false),
    ('Auditor', 'calendar', false, false, false, false, false),
    ('Auditor', 'communication', false, false, false, false, false),
    ('Auditor', 'reports', true, false, false, false, false)
)
insert into role_permissions (role_id, module, can_view, can_add, can_edit, can_delete, can_approve)
select r.id, p.module, p.can_view, p.can_add, p.can_edit, p.can_delete, p.can_approve
from perms p
join roles r on r.name = p.role_name;
